name = "mophrase"
main = "src/index.ts"
compatibility_date = "2026-01-12"
workers_dev = true
preview_urls = false

[assets]
directory = "../dist"
binding = "ASSETS"

[vars]
# 本番では `wrangler secret put` を使って設定してください
# OPENAI_API_KEY = ""
# GEMINI_API_KEY = ""
